language: ruby
sudo: false
script: bundle exec rake test
branches:
  except:
  - "/\\Av\\d+\\Z/"
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.0
    gemfile: Gemfile
  - rvm: 2.3.0
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.4.0
    gemfile: Gemfile
  - rvm: 2.4.0
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.5.0
    gemfile: Gemfile
  - rvm: 2.5.0
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.6.6
    gemfile: Gemfile
  - rvm: 2.6.6
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.7.2
    gemfile: Gemfile
  - rvm: 2.7.2
    gemfile: gemfiles/Gemfile-edge
  - rvm: 3.0.0
    gemfile: gemfiles/Gemfile-edge
  - rvm: jruby-head
    gemfile: Gemfile
# ppc64le specific changes
  - rvm: 2.3.0
    gemfile: Gemfile
    arch: ppc64le
  - rvm: 2.3.0
    arch: ppc64le
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.4.0
    arch: ppc64le
    gemfile: Gemfile
  - rvm: 2.4.0
    arch: ppc64le
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.5.0
    arch: ppc64le
    gemfile: Gemfile
  - rvm: 2.5.0
    arch: ppc64le
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.6.6
    arch: ppc64le
    gemfile: Gemfile
  - rvm: 2.6.6
    arch: ppc64le
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.7.2
    arch: ppc64le
    gemfile: Gemfile
  - rvm: 2.7.2
    arch: ppc64le
    gemfile: gemfiles/Gemfile-edge
  - rvm: jruby-head
    arch: ppc64le
    gemfile: Gemfile
    
  allow_failures:
  - rvm: jruby-head
    gemfile: Gemfile
  - rvm: 2.2.0
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.3.0
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.4.0
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.5.0
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.6.6
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.7.2
    gemfile: gemfiles/Gemfile-edge
# ppc64le specific changes
  - rvm: jruby-head
    arch: ppc64le
    gemfile: Gemfile
  - rvm: 2.2.0
    arch: ppc64le
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.3.0
    arch: ppc64le
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.4.0
    arch: ppc64le
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.5.0
    arch: ppc64le
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.6.6
    arch: ppc64le
    gemfile: gemfiles/Gemfile-edge
  - rvm: 2.7.2
    arch: ppc64le
    gemfile: gemfiles/Gemfile-edge
notifications:
  email: false
  irc:
    channels:
    - irc.freenode.org#ruby-fog
    template:
    - "[#%{build_number}] %{message} %{build_url}"
    - "[#%{build_number}] %{commit} on %{branch} by %{author}"
    - "[#%{build_number}] %{compare_url}"
    on_success: always
    on_failure: always
    use_notice: false
before_install:
  - gem update bundler
env:
  global:
    secure: LlDKdKSRo3sEjQ55XesbOXhKZ3RrOtqoD1ZL8Wx39K3iVzeEV3Kc8HjDfEvo7R4pOc3BMTNJcputklVEPN0FkWGN7Py+OEtbHj3IZl0MX+KEWNk0gU+4+sgPrL1eXUQyMUSkCrBsKg08rPel4KMYUOXbtnLyUU9PDbBwm4LJYOc=
after_success:
  - bundle exec codeclimate-test-reporter
