name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday.

permissions:
  contents: read

jobs:
  Shared:
    uses: fog/.github/.github/workflows/ci.yml@v1.5.0
